### ISSUE TITLE
Please make proxy or VPN functionality

### ISSUE THREAD

**Issue by THEBIGMISHA** [reisxd/TizenBrew#31] opened 2024-09-15 16:23 UTC
In my region they started blocking YouTube and on Tizen OS there is no way to bypass it because this OS does not support Proxy or VPN

**Comment by reisxd** [comment] 2024-09-15 16:25
Duplicate of https://github.com/reisxd/TizenTube/issues/84

**Closed by reisxd** 2024-09-15 16:25 UTC
